DailyMail:
  cron: 20 08 * * *
  class: DailyMail
  queue: mailer
  args: 
  description: Send daily mail

WeeklyMail:
  cron: 30 08 * * 1
  class: WeeklyMail
  queue: mailer
  args: 
  description: Send weekly mail

WeeklyMilestone:
  cron: 00 08 * * 1
  class: WeeklyMilestone
  queue: mailer
  args: 
  description: Auto create milestone and tag every week
