DailyMail:
  cron: 20 08 * * *
  class: DailyMail
  queue: mailer
  args: 
  description: Send daily mail

WeeklyMail:
  cron: 30 08 * * 1
  class: WeeklyMail
  queue: mailer
  args: 
  description: Send daily mail
